/** @type {import("jest").Config} **/
export default {
  testEnvironment: "node",
  transform: {
    "^.+\\.tsx?$": ["ts-jest", { tsconfig: "<rootDir>/tests/tsconfig.test.json" }],
  },
  moduleNameMapper: {
    "^\\./routes/api\\.js$": "<rootDir>/src/routes/api.ts",
    "^\\.\\./db/client\\.js$": "<rootDir>/src/db/client.ts",
    "^\\.\\./featureDetail\\.js$": "<rootDir>/src/services/featureDetail.ts",
    "^\\./apiTypes\\.js$": "<rootDir>/src/routes/apiTypes.ts",
    "^\\.\\./config\\.js$": "<rootDir>/src/config.ts",
    "^\\.\\./geometry\\.js$": "<rootDir>/src/services/geometry.ts",
    "^\\.\\./utils\\.js$": "<rootDir>/src/services/utils.ts",
    "^\\.\\./scene/sceneObject\\.js$": "<rootDir>/src/services/scene/sceneObject.ts",
    "^\\.\\./scene/scenePrompt\\.js$": "<rootDir>/src/services/scene/scenePrompt.ts",
    "^\\./osmGate\\.js$": "<rootDir>/src/services/osmNormalization/osmGate.ts",
    "^\\./osmNormalizer\\.js$": "<rootDir>/src/services/osmNormalization/osmNormalizer.ts",
    "^\\./osmNormalizedToDb\\.js$": "<rootDir>/src/services/osmNormalization/osmNormalizedToDb.ts",
    "^\\./polarViewObject\\.js$": "<rootDir>/src/services/scene/polarViewObject.ts",
    "^\\./polarViewOcclusion\\.js$": "<rootDir>/src/services/scene/polarViewOcclusion.ts",
    "^\\.\\./scene/polarViewPrompt\\.js$": "<rootDir>/src/services/scene/polarViewPrompt.ts",
    "^\\./sceneUtilLabel\\.js$": "<rootDir>/src/services/scene/sceneUtilLabel.ts",
    "^\\.\\./buildingGeneration/(.*)\\.js$": "<rootDir>/src/services/buildingGeneration/$1.ts",
    "^\\.\\./gameSystem/(.*)\\.js$": "<rootDir>/src/services/gameSystem/$1.ts",
    "^\\./systemPrompts\\.js$": "<rootDir>/src/services/gameSystem/systemPrompts.ts",
    "^\\./gameDebug\\.js$": "<rootDir>/src/services/gameSystem/gameDebug.ts",
    "^\\./llm\\.js$": "<rootDir>/src/services/gameSystem/llm.ts",
    "^\\./gameSessionStore\\.js$": "<rootDir>/src/services/gameSystem/gameSessionStore.ts",
    "^\\./agentBookComposer\\.js$": "<rootDir>/src/services/gameSystem/agentBookComposer.ts",
    "^\\./agentStateManager\\.js$": "<rootDir>/src/services/gameSystem/agentStateManager.ts",
    "^\\./agentVisualDescriber\\.js$": "<rootDir>/src/services/gameSystem/agentVisualDescriber.ts",
    "^\\./toolActiveIndoorLocations\\.js$": "<rootDir>/src/services/gameSystem/toolActiveIndoorLocations.ts",
    "^\\./toolMovePlayer\\.js$": "<rootDir>/src/services/gameSystem/toolMovePlayer.ts",
    "^\\./toolIndoorPosition\\.js$": "<rootDir>/src/services/gameSystem/toolIndoorPosition.ts",
    "^\\./buildingRecord\\.js$": "<rootDir>/src/services/buildingGeneration/buildingRecord.ts",
    "^\\./buildingSchema\\.js$": "<rootDir>/src/services/buildingGeneration/buildingSchema.ts",
    "^\\./buildingApartment\\.js$": "<rootDir>/src/services/buildingGeneration/buildingApartment.ts",
    "^\\./buildingApartmentUtility\\.js$": "<rootDir>/src/services/buildingGeneration/buildingApartmentUtility.ts",
    "^\\./buildingHouse\\.js$": "<rootDir>/src/services/buildingGeneration/buildingHouse.ts",
    "^\\./buildingHouseAccessory\\.js$": "<rootDir>/src/services/buildingGeneration/buildingHouseAccessory.ts",
    "^\\./buildingUtils\\.js$": "<rootDir>/src/services/buildingGeneration/buildingUtils.ts",
    "^@/(.*)\\.js$": "<rootDir>/src/$1.ts",
  },
};
